[tool.poetry]
name = "nlp-training"
version = "0.1.0"
description = "NLP training repository."
authors = ["Carlos Alves, Daniel Ferrari and Tomás Osório"]

[tool.poetry.dependencies]
python = "^3.9"

mlflow = "^1.24.0"
nlpaug = "^1.1.10"
nltk = "^3.7"
pytorch-lightning = "^1.5.10"
sacremoses = "^0.0.47"
setuptools = "59.5.0"
torchmetrics = "^0.7.2"
torchtext = "^0.11.2"
tqdm = "^4.63.0"
nlpiper = "^0.2.1"

[tool.poetry.dev-dependencies]
pydocstyle = "^6.1.1"
pytest = "^7.0.1"
pytest-cov = "^3.0.0"
mypy = "^0.931"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
