[tool.poetry]
name = "nlp-training"
version = "0.1.0"
description = ""
authors = ["Carlos Alves, Daniel Ferrari, Tomás Osório"]

[tool.poetry.dependencies]
python = "^3.9"
pytorch-lightning = { version = "^1.5.10", optional = true }
torchtext = { version = "^0.11.2", optional = true }
torchmetrics = { version = "^0.7.2", optional = true }
setuptools = "59.5.0"
nlpiper = "^0.2.0"

[tool.poetry.extras]
training = [
    "pytorch-lightning",
    "torchtext",
    "torchmetrics"
]

[tool.poetry.dev-dependencies]
pydocstyle = "^6.1.1"
pytest = "^7.0.1"
pytest-cov = "^3.0.0"
mypy = "^0.931"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
